# Mainnet preset - Altair

CONFIG_NAME: "mainnet"

# Updated penalty values
# ---------------------------------------------------------------
# 3 * 2**24) (= 50,331,648)
ALTAIR_INACTIVITY_PENALTY_QUOTIENT: 50331648
# 2**6 (= 64)
ALTAIR_MIN_SLASHING_PENALTY_QUOTIENT: 64
# 2
ALTAIR_PROPORTIONAL_SLASHING_MULTIPLIER: 2


# Misc
# ---------------------------------------------------------------
# 2**10 (=1,024)
SYNC_COMMITTEE_SIZE: 1024
# 2**6 (=64)
SYNC_SUBCOMMITTEE_SIZE: 64


# Time parameters
# ---------------------------------------------------------------
# 2**8 (= 256)
EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 256


# Signature domains
# ---------------------------------------------------------------
DOMAIN_SYNC_COMMITTEE: 0x07000000
